export const ADD_COMPLAINT_START = "ADD_COMPLAINT_START";
export const ADD_COMPLAINT_SUCCESS = "ADD_COMPLAINT_SUCCESS";
export const ADD_COMPLAINT_FAIL = "ADD_COMPLAINT_FAIL";

export const GET_POSTOFFICE_START="GET_POSTOFFICE_START";
export const GET_POSTOFFICE_SUCCESS="GET_POSTOFFICE_SUCCESS";
export const GET_POSTOFFICE_FAIL="GET_POSTOFFICE_FAIL";

export const GET_PID_START="GET_PID_START";
export const GET_PID_SUCCESS="GET_PID_SUCCESS";
export const GET_PID_FAIL="GET_PID_FAIL";